repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
  - id: black-jupyter
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.9.1
  hooks:
  - id: nbqa-isort
  - id: nbqa-mypy
    args: [--ignore-missing-imports]
