name: beehive
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - ipython>=8
  - jupyterlab>=3
  - black
  - isort
  - jupyterlab_code_formatter
  - mypy
  - nbqa
  - pandas>=1.4
  - pillow
  - pip>=22
  - pre-commit
  - git
  - pip:
    - black-nb
    - mutf8
    - nbt==1.5.1
    - ffmpeg-python  # conda dep will install conda ffmpeg which we don't want
