name: beehive
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - ipython>=8
  - jupyterlab>=3
  - black
  - isort
  - jupyterlab_code_formatter
  - mypy
  - pandas>=1.4
  - ffmpeg-python
  - pillow
  - pip>=22
  - pre-commit
  - pip:
    - black-nb
    - mutf8
    - nbt==1.5.1
